/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class coursier_jniutils_windowsknownfolders_WindowsKnownFolders */

#ifndef _Included_coursier_jniutils_windowsknownfolders_WindowsKnownFolders
#define _Included_coursier_jniutils_windowsknownfolders_WindowsKnownFolders
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     coursier_jniutils_windowsknownfolders_WindowsKnownFolders
 * Method:    GetKnownFolderPath
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursier_jniutils_windowsknownfolders_WindowsKnownFolders_GetKnownFolderPath
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
