/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class coursier_jniutils_windowsansiterminal_WindowsAnsiTerminal */

#ifndef _Included_coursier_jniutils_windowsansiterminal_WindowsAnsiTerminal
#define _Included_coursier_jniutils_windowsansiterminal_WindowsAnsiTerminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     coursier_jniutils_windowsansiterminal_WindowsAnsiTerminal
 * Method:    terminalSizeNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursier_jniutils_windowsansiterminal_WindowsAnsiTerminal_terminalSizeNative
  (JNIEnv *, jclass);

/*
 * Class:     coursier_jniutils_windowsansiterminal_WindowsAnsiTerminal
 * Method:    enableAnsiOutputNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursier_jniutils_windowsansiterminal_WindowsAnsiTerminal_enableAnsiOutputNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
