/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables */

#ifndef _Included_coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables
#define _Included_coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables
 * Method:    GetUserEnvironmentVariableNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables_GetUserEnvironmentVariableNative
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables
 * Method:    SetUserEnvironmentVariableNative
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables_SetUserEnvironmentVariableNative
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables
 * Method:    DeleteUserEnvironmentVariableNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables_DeleteUserEnvironmentVariableNative
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
