/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class coursierapi_internal_jniutils_NativeCalls */

#ifndef _Included_coursierapi_internal_jniutils_NativeCalls
#define _Included_coursierapi_internal_jniutils_NativeCalls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     coursierapi_internal_jniutils_NativeCalls
 * Method:    terminalSizeNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursierapi_internal_jniutils_NativeCalls_terminalSizeNative
  (JNIEnv *, jclass);

/*
 * Class:     coursierapi_internal_jniutils_NativeCalls
 * Method:    enableAnsiOutputNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursierapi_internal_jniutils_NativeCalls_enableAnsiOutputNative
  (JNIEnv *, jclass);

/*
 * Class:     coursierapi_internal_jniutils_NativeCalls
 * Method:    GetUserEnvironmentVariableNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_coursierapi_internal_jniutils_NativeCalls_GetUserEnvironmentVariableNative
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     coursierapi_internal_jniutils_NativeCalls
 * Method:    SetUserEnvironmentVariableNative
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_coursierapi_internal_jniutils_NativeCalls_SetUserEnvironmentVariableNative
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     coursierapi_internal_jniutils_NativeCalls
 * Method:    DeleteUserEnvironmentVariableNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_coursierapi_internal_jniutils_NativeCalls_DeleteUserEnvironmentVariableNative
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     coursierapi_internal_jniutils_NativeCalls
 * Method:    GetKnownFolderPathNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursierapi_internal_jniutils_NativeCalls_GetKnownFolderPathNative
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
