/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class coursier_bootstrap_launcher_jniutils_BootstrapNativeApi */

#ifndef _Included_coursier_bootstrap_launcher_jniutils_BootstrapNativeApi
#define _Included_coursier_bootstrap_launcher_jniutils_BootstrapNativeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     coursier_bootstrap_launcher_jniutils_BootstrapNativeApi
 * Method:    terminalSizeNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursier_bootstrap_launcher_jniutils_BootstrapNativeApi_terminalSizeNative
  (JNIEnv *, jclass);

/*
 * Class:     coursier_bootstrap_launcher_jniutils_BootstrapNativeApi
 * Method:    enableAnsiOutputNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursier_bootstrap_launcher_jniutils_BootstrapNativeApi_enableAnsiOutputNative
  (JNIEnv *, jclass);

/*
 * Class:     coursier_bootstrap_launcher_jniutils_BootstrapNativeApi
 * Method:    GetUserEnvironmentVariableNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_coursier_bootstrap_launcher_jniutils_BootstrapNativeApi_GetUserEnvironmentVariableNative
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     coursier_bootstrap_launcher_jniutils_BootstrapNativeApi
 * Method:    SetUserEnvironmentVariableNative
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_coursier_bootstrap_launcher_jniutils_BootstrapNativeApi_SetUserEnvironmentVariableNative
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     coursier_bootstrap_launcher_jniutils_BootstrapNativeApi
 * Method:    DeleteUserEnvironmentVariableNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_coursier_bootstrap_launcher_jniutils_BootstrapNativeApi_DeleteUserEnvironmentVariableNative
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     coursier_bootstrap_launcher_jniutils_BootstrapNativeApi
 * Method:    GetKnownFolderPathNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursier_bootstrap_launcher_jniutils_BootstrapNativeApi_GetKnownFolderPathNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     coursier_bootstrap_launcher_jniutils_BootstrapNativeApi
 * Method:    GetModuleFileNameNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursier_bootstrap_launcher_jniutils_BootstrapNativeApi_GetModuleFileNameNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
