/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables */

#ifndef _Included_coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables
#define _Included_coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables
 * Method:    GetUserEnvironmentVariableNative
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables_GetUserEnvironmentVariableNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables
 * Method:    SetUserEnvironmentVariableNative
 * Signature: (Ljava/lang/String;[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_coursier_jniutils_windowsenvironmentvariables_WindowsEnvironmentVariables_SetUserEnvironmentVariableNative
  (JNIEnv *, jclass, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
